proyecto_inmuebles/gestion_inmuebles/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.indice, name="indice"),
    path("contacto/", views.contacto, name="contacto"),
    path("exito/", views.exito, name="exito"),
    path("arriendos/", views.arriendos, name="arriendos"),
    path("buscar-ciudades/", views.buscar_ciudades, name="buscar_ciudades"),
    path("buscar_inmuebles/", views.buscar_inmuebles, name="buscar_inmuebles"),
    path("registro/", views.register, name="registro"),
    path("misdatos/", views.misdatos, name="misdatos"),
    path("editar/", views.update_profile, name="update_profile"),
    path("dashboard_prop/", views.mostrar_inmuebles, name="dashboard_prop"),
    path("add_propiedad/", views.add_inmuebles, name="agregar_propiedad"),
    path(
        "mostrar_un_inmuebles/<int:inmueble_id>/",
        views.mostrar_un_inmuebles,
        name="mostrar_un_inmuebles",
    ),
    path(
        "request_property/<int:id_propiedad>/",
        views.request_property,
        name="request_property",
    ),
    path("my_requests/", views.my_requests, name="my_requests"),
    path(
        "delete_request/<int:solicitud_id>/",
        views.delete_request,
        name="delete_request",
    ),
    path("my_requests_owner/", views.my_requests_owner, name="my_requests_owner"),
    path(
        "accept_request/<int:solicitud_id>/",
        views.accept_request,
        name="accept_request",
    ),
    path(
        "reject_request/<int:solicitud_id>/",
        views.reject_request,
        name="reject_request",
    ),
    path(
        "habilitar_request/<int:inmueble_id>/",
        views.habilitar_request,
        name="habilitar_request",
    ),
    # ajax para mostrar ciudades, estados
    path("ajax/cargar-estados/", views.cargar_estados, name="ajax_cargar_estados"),
    path("ajax/cargar-ciudades/", views.cargar_ciudades, name="ajax_cargar_ciudades"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_inmuebles/proyecto_inmuebles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path("admin/", admin.site.urls),
    
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),

    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("", include("gestion_inmuebles.urls")),
]

proyecto_inmuebles/gestion_inmuebles/models.py
from django.db import models

# from django.contrib.auth.models import AbstractUser #User

from django.contrib.auth.models import User


import uuid


class Pais(models.Model):
    id = models.AutoField(primary_key=True)  # Campo ID como clave primaria
    nombre = models.CharField(max_length=50)
    codigo = models.CharField(max_length=3, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre}"


class EstadoProvincia(models.Model):
    id = models.AutoField(primary_key=True)  # Campo ID como clave primaria
    nombre = models.CharField(max_length=50)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.nombre}, {self.pais.nombre}"


class Ciudad(models.Model):
    id = models.AutoField(primary_key=True)  # Campo ID como clave primaria
    nombre = models.CharField(max_length=150)
    estado_provincia = models.ForeignKey(EstadoProvincia, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.nombre}, {self.estado_provincia.nombre}"


class TipoInmueble(models.Model):
    # TIPOS_INMUEBLE = (
    #     ('casa', 'casa'),
    #     ('departamento', 'departamento'),
    #     ('parcela', 'parcela')
    #     )
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nombre}"


class Inmueble(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = (
        models.TextField()
    )  # Cambiado a TextField para permitir descripciones más largas
    m2_construidos = models.IntegerField()
    m2_totales = models.IntegerField()
    n_estacionamientos = models.IntegerField()
    n_habitaciones = models.IntegerField()
    n_baños = models.IntegerField()
    precio = models.DecimalField(
        max_digits=10, decimal_places=2
    )  # Cambio a DecimalField para mayor precisión
    moneda = models.CharField(
        max_length=3, default="USD"
    )  # ISO 4217 currency code, e.g., 'USD', 'EUR'
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    calle = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    ciudad = models.ForeignKey(
        to=Ciudad, on_delete=models.PROTECT
    )  # Referencia como string
    codigo_postal = models.CharField(max_length=20, null=True, blank=True)
    latitud = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True
    )  # los agregue con el fin de usar eventualmente googlemaps para ubicacion
    longitud = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True
    )  # los agregue con el fin de usar eventualmente googlemaps para ubicacion
    disponible = models.BooleanField(default=True)
    tipo_inmueble = models.ForeignKey(TipoInmueble, on_delete=models.PROTECT)
    propietario = models.ForeignKey(
        User, null=False, blank=False, default="1", on_delete=models.RESTRICT
    )

    def __str__(self):
        return f"{self.nombre} - {self.calle}"


class ImagenInmueble(models.Model):
    propiedad = models.ForeignKey(Inmueble, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="propiedades/")


class TipoUsuario(models.Model):
    TIPOS_USUARIO = (
        # ("0", "Nulo"),
        ("1", "Arrendador"),
        ("2", "Arrendatario"),
        # ("3", "Administrador"),
    )
    tipo = models.CharField(max_length=20, choices=TIPOS_USUARIO, default="Nulo")

    def __str__(self):
        return self.get_tipo_display()


class PerfilUsuario(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="perfil"
    )  # Relación uno a uno con User
    telefono = models.CharField(
        max_length=15, unique=False, blank=True, null=True
    )  # Campo adicional
    direccion = models.CharField(
        max_length=150, blank=True, null=True
    )  # Campo adicional
    id_nacional = models.CharField(
        max_length=20, unique=True, blank=True, null=True
    )  # Identificador adicional
    tipo_usuario = models.ForeignKey(
        TipoUsuario, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"Perfil de {self.user.username}"


class Solicitud(models.Model):
    inmueble = models.ForeignKey(Inmueble, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, default="en espera")

    def __str__(self):
        return f"{self.usuario.id_nacional} - {self.inmueble.nombre}"


class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    customer_name = models.CharField(max_length=64)
    customer_email = models.EmailField()
    message = models.TextField()

proyecto_inmuebles/gestion_inmuebles/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)  # get_object_or_404 para filtrar un elemento

from .models import PerfilUsuario
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect
from .models import ContactForm
from .forms import (
    ContactFormForm,
    UserUpdateForm,
    PerfilUpdateForm,
    FotoInmuebleForm,
    InmuebleUpdateForm,
)

from django.contrib import messages
from .forms import RegistroForm
from django.contrib.auth import login

# from .forms import RegistroUser

# buscador
from django.http import JsonResponse
from .models import (
    Inmueble,
    Ciudad,
    ImagenInmueble,
    TipoInmueble,
    EstadoProvincia,
    Solicitud,
)
from django.http import JsonResponse
from .models import PerfilUsuario


# Create your views here.
def indice(request):
    inmuebles = Inmueble.objects.filter(disponible=True).order_by("?")[
        :6
    ]  # Selecciona 4 inmuebles aleatorios

    # fotos del inmueble
    inmuebles_con_imagenes = []
    for inmueble in inmuebles:
        imagen = ImagenInmueble.objects.filter(
            propiedad=inmueble
        ).first()  # Obtener solo la primera imagen
        inmuebles_con_imagenes.append(
            {
                "inmueble": inmueble,
                "imagen": imagen,
                "ciudad": inmueble.ciudad.nombre,
                "descripcion": inmueble.descripcion,
            }
        )

    context = {
        "inmuebles_con_imagenes": inmuebles_con_imagenes,
        # "ciudades": Ciudad.objects.all(),  # Para mostrar las ciudades en el menú desplegable
    }
    if request.user.is_authenticated:
        perfil = PerfilUsuario.objects.get(user=request.user)

        # Gurda el nombre de usuario y tipo de usuario en la sesion
        request.session["usuario"] = request.user.username
        request.session["tipo_usuario"] = perfil.tipo_usuario.tipo
        tipo_usuario = request.session.get("tipo_usuario")
        print(tipo_usuario)
        context = {
            "inmuebles_con_imagenes": inmuebles_con_imagenes,
            "usuario": request.session.get("usuario"),
            "tipo_usuario": tipo_usuario,
            # "ciudades": Ciudad.objects.all(),  # Para mostrar las ciudades en el menú desplegable
        }
        return render(
            request,
            "index.html",
            context,
            # {"usuario": request.session.get("usuario"), "tipo_usuario": tipo_usuario},
        )

        # return render(request, 'index.html', {'usuario': request.session.get('usuario'), 'tipo_usuario':tipo_usuario })

    return render(request, "index.html", context)


def contacto(request):
    if request.method == "GET":
        form = ContactFormForm()
    else:
        # para el formulario normal
        form = ContactFormForm(request.POST)
        # para el formulario modal
        # form = ContactFormModelForm(request.POST)
        if form.is_valid():
            contact_form = ContactForm.objects.create(**form.cleaned_data)
            return HttpResponseRedirect("/exito/")

    return render(request, "contactoM.html", {"form": form})


def exito(request):
    return render(request, "exito.html")


def register(request):
    if request.method == "POST":
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("indice")
    else:
        form = RegistroForm()
    return render(
        request, template_name="registration/register.html", context={"form": form}
    )


def buscar_ciudades(request):
    query = request.GET.get("q", "")

    # Filtrar las ciudades con inmuebles disponibles
    if query:
        # inmuebles disponibles
        ciudades = Ciudad.objects.filter(
            nombre__icontains=query, inmueble__disponible=True
        ).distinct()
    else:
        ciudades = []

    # Construir la lista de resultados con la jerarquía de Ciudad -> Estado -> País
    resultados = [
        {
            "nombre": ciudad.nombre,
            "estado": ciudad.estado_provincia.nombre,
            "pais": ciudad.estado_provincia.pais.nombre,
            "id": ciudad.id,
        }
        for ciudad in ciudades
    ]

    return JsonResponse({"resultados": resultados})


def buscar_inmuebles(request):
    ciudad_id = request.GET.get("ciudad_id")

    if ciudad_id:
        # Filtrar inmuebles disponibles en la ciudad seleccionada
        inmuebles = Inmueble.objects.filter(ciudad_id=ciudad_id, disponible=True)
    else:
        inmuebles = Inmueble.objects.filter(
            disponible=True
        )  # listado de inmuebles de la ciudad seleccionada

    # fotos del inmueble
    inmuebles_con_imagenes = []
    for inmueble in inmuebles:
        imagenes = ImagenInmueble.objects.filter(propiedad=inmueble)
        inmuebles_con_imagenes.append({"inmueble": inmueble, "imagenes": imagenes})

    context = {
        "inmuebles_con_imagenes": inmuebles_con_imagenes,
        "ciudades": Ciudad.objects.all(),  # Para mostrar las ciudades en el menú desplegable
    }

    return render(request, "arriendos.html", context)


def arriendos(request):
    tusuario = request.session.get("tipo_usuario")
    if not tusuario:
        # Si no hay usuario en la sesión, redirigir al login
        return redirect("login")
    return render(request, "arriendos.html")


# actualizar datos del perfil
def misdatos(request):
    perfil = PerfilUsuario.objects.get(user=request.user)
    TIPOS_USUARIO = (
        # ("0", "Nulo"),
        ("1", "Arrendador"),
        ("2", "Arrendatario"),
        # ("3", "Administrador"),
    )
    # se envia por parametro los 2 modelos
    context = {
        "user": request.user,  # Datos del user de django
        "perfil": perfil,  # Datos perfilusuario
        # ,'tipo_usuario': tipousuario
    }
    return render(request, "misdatos.html", context)


@login_required
def update_profile(request):
    # Obtener o crear el perfil del usuario si no existe
    perfil, created = PerfilUsuario.objects.get_or_create(user=request.user)

    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        perfil_form = PerfilUpdateForm(request.POST, instance=perfil)

        if user_form.is_valid() and perfil_form.is_valid():
            user_form.save()
            perfil_form.save()
            messages.success(request, "Tu perfil ha sido actualizado.")
            return redirect("misdatos")
            # return redirect("update_profile")
    else:
        user_form = UserUpdateForm(instance=request.user)
        perfil_form = PerfilUpdateForm(instance=perfil)

    context = {"user_form": user_form, "perfil_form": perfil_form}
    return render(request, "update_profile.html", context)


def mostrar_inmuebles(request):

    inmuebles = Inmueble.objects.filter(propietario=request.user)

    # fotos del inmueble
    inmuebles_con_imagenes = []
    for inmueble in inmuebles:
        print(inmueble.pk)
        imagenes = ImagenInmueble.objects.filter(propiedad=inmueble)
        tipoinmueble = inmueble.tipo_inmueble
        # tipoinmueble = TipoInmueble.objects.filter(TipoInmueble =inmuebles.tipo_inmueble)
        inmuebles_con_imagenes.append(
            {"inmueble": inmueble, "imagenes": imagenes, "tipoinmueble": tipoinmueble}
        )

    context = {
        "inmuebles_con_imagenes": inmuebles_con_imagenes,
        #        'ciudades': Ciudad.objects.all()  # Para mostrar las ciudades en el menú desplegable
    }

    return render(request, "propiedades.html", context)


def add_inmuebles(request):
    if request.method == "POST":
        print(request.POST)
        print("request")

        # <QueryDict: {'csrfmiddlewaretoken': ['jAozsiNu8dx7lnLzDfb3xRg9w2grR04JeFQ8zPvmG6vFEgABW0KbBI9QXtezhzkw'], 'nombre': ['propiedadX'], 'descripcion': ['x'], 'm2_construidos': ['56'], 'm2_totales': ['456'], 'n_estacionamientos': ['2'], 'n_habitaciones': ['2'], 'n_baños': ['1'], 'precio': ['23432432'], 'moneda': ['USD'], 'calle': ['gncbcbncv'], 'numero': ['54'], 'pais': ['5'], 'estado_provincia': ['1833'], 'ciudad': ['565420'], 'codigo_postal': ['5635653'], 'tipo_inmueble': ['1'], 'data_submit': ['']}>

        # {'nombre': "['propiedadX']", 'descripcion': "['X']", 'calle': "['por ahi']", 'numero': "['77']", 'codigo_postal': "['5310144']"}

        formInmueble = InmuebleUpdateForm(request.POST)
        # print(formInmueble)
        if formInmueble.is_valid():

            inmueble = formInmueble.save(commit=False)
            inmueble.propietario = request.user
            # Asegurando de que los campos estén correctamente asignados Probando fix
            inmueble.ciudad = formInmueble.cleaned_data["ciudad"]
            inmueble.estado_provincia = formInmueble.cleaned_data["estado_provincia"]
            inmueble.pais = formInmueble.cleaned_data["pais"]
            inmueble.save()
            # print("graba")
            messages.success(request, "Tu inmueble ha sido actualizado.")
            return redirect("dashboard_prop")
        else:
            print(formInmueble.errors)
            messages.error(request, "Hay errores en los datos")
    else:
        # formInmueble = InmuebleUpdateForm(instance=request.user)
        formInmueble = InmuebleUpdateForm()
    #  return redirect("dashboard_prop")
    context = {"formInmueble": formInmueble}
    return render(request, "add_propiedad.html", context)


def cargar_estados(request):
    pais_id = request.GET.get("pais_id")
    estados = EstadoProvincia.objects.filter(pais_id=pais_id).order_by("nombre")
    return JsonResponse(list(estados.values("id", "nombre")), safe=False)


def cargar_ciudades(request):
    estado_id = request.GET.get("estado_id")
    ciudades = Ciudad.objects.filter(estado_provincia_id=estado_id).order_by("nombre")

proyecto_inmuebles/gestion_inmuebles/templates/add_fotoinmueble.html
{% extends 'layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Actualizar estados cuando se selecciona un país
        $('#id_pais').change(function () {
            var url = "{% url 'ajax_cargar_estados' %}";
            var paisId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pais_id': paisId
                },
                success: function (data) {
                    $('#id_estado').html('<option value="">Selecciona un estado/provincia</option>');
                    $.each(data, function (key, value) {
                        $('#id_estado').append('<option value="' + value.id + '">' + value.nombre + '</option>');
                    });
                }
            });
        });

        // Actualizar ciudades cuando se selecciona un estado
        $('#id_estado').change(function () {
            var url = "{% url 'ajax_cargar_ciudades' %}";
            var estadoId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'estado_id': estadoId
                },
                success: function (data) {
                    $('#id_ciudad').html('<option value="">Selecciona una ciudad</option>');
                    $.each(data, function (key, value) {
                        $('#id_ciudad').append('<option value="' + value.id + '">' + value.nombre + '</option>');
                    });
                }
            });
        });
    });
</script>


<section id="propiedad">
<h2>Propiedad</h2>
<a href="{% url 'agregar_propiedad' %}">Agregar Inmuebles</a>
<ul>

    <li>
        <strong>{{ tipoinmueble.nombre }}</strong>
        <br>
        <strong>{{ inmueble.nombre }}</strong> - {{ inmueble.descripcion }} - {{ inmueble.precio }} {{ inmueble.moneda }}
        <br>
        Dirección: {{ inmueble.calle }} {{ inmueble.numero }}, {{ inmueble.ciudad.nombre }}
        <br>
        m2 construidos:  {{ inmueble.m2_construidos }} - m2 totales : {{ inmueble.m2_totales }}
        <br>
        estacionamientos : {{ inmueble.n_estacionamientos }}
        <br>
        habitaciones : {{ inmueble.n_habitaciones }} -  baños : {{ inmueble.n_baños }}

        <section id="propiedad_edit">

            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="card shadow-lg">
                    <div class="card-header text-center bg-primary text-white">
                      <h5 class="mb-0">Modificar Data Inmueble</h5>
                    </div>
                    <form method="POST" >
                      {% csrf_token %}
                      {{ formInmueble.as_p }}
                        <!-- Formulario del Perfil - - >
                        { { perfil_form|crispy }} -->
                      </div>
                      <div class="d-grid gap-2">
                        <button type="submit" name="data_submit" class="btn btn-primary btn-lg">
                          Guardar cambios
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
    </section> 
    <section id="Fotos_Actuales">       
        <br><a href="">Modificar Inmuebles</a>--<a href="">Agregar Fotografia</a>
        <!-- Carrusel de imágenes en miniatura -->
        {% if imagenes %}
            <div class="row">
                
                {% for imagen in imagenes %}
                    <!-- para manipular un contador de elementos y saber donde agregar fila-->
                    {% if forloop.counter0|divisibleby:4 and not forloop.first %}
                        </div><div class="row">
                    {% endif %}
                    <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">Foto {{ i }}</h5>
                        <img id="prop-min" src="{{ imagen.imagen.url }}" class="d-block w-auto"  alt="Imagen de {{ item.inmueble.nombre }}">
                        <a href="#" class="btn btn-primary">Eliminar Foto</a>
                        </div>
                    </div>
                    </div>
                   
                {% endfor %}

            </div>



        {% else %}
        <p>Imágenes no disponibles</p>
        {% endif %}
    </li>

</ul>
</section>
<section id="foto">

        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-6">
              <div class="card shadow-lg">
                <div class="card-header text-center bg-primary text-white">
                  <h5 class="mb-0">Agregar Fotos</h5>
                </div>
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                    <!-- Formulario del Perfil - - >
                    { { perfil_form|crispy }} -->
                  </div>
                  <div class="d-grid gap-2">
                    <button type="submit" name="foto_submit" class="btn btn-primary btn-lg">
                      Guardar cambios
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
</section>


{% endblock %}

proyecto_inmuebles/gestion_inmuebles/templates/add_propiedad.html
{% extends 'layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Actualizar estados cuando se selecciona un país
        $('#id_pais').change(function () {
            var url = "{% url 'ajax_cargar_estados' %}";
            var paisId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pais_id': paisId
                },
                success: function (data) {
                    $('#id_estado').html('<option value="">Selecciona un estado/provincia</option>');
                    $.each(data, function (key, value) {
                        $('#id_estado').append('<option value="' + value.id + '">' + value.nombre + '</option>');
                    });
                }
            });
        });

        // Actualizar ciudades cuando se selecciona un estado
        $('#id_estado').change(function () {
            var url = "{% url 'ajax_cargar_ciudades' %}";
            var estadoId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'estado_id': estadoId
                },
                success: function (data) {
                    $('#id_ciudad').html('<option value="">Selecciona una ciudad</option>');
                    $.each(data, function (key, value) {
                        $('#id_ciudad').append('<option value="' + value.id + '">' + value.nombre + '</option>');
                    });
                }
            });
        });
    });
</script>


<section id="propiedad">
<h2>Propiedad</h2>

            <div class="container">
              {% if messages %}
              <div class="alert alert-danger text-center" role="alert">
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
              </div>
              {% endif %}

              {% if formInmueble.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field in formInmueble %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}
              <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="card shadow-lg">
                    <div class="card-header text-center bg-primary text-white">
                      <h5 class="mb-0">Agregar Data Inmueble</h5>
                    </div>
                    <form method="POST" >
                      {% csrf_token %}
                      {{ formInmueble.as_p }}
                        <!-- Formulario del Perfil - - >
                        { { perfil_form|crispy }} -->
                      {% comment %} </div> {% endcomment %}
                      <div class="d-grid gap-2">
                        <button type="submit" name="data_submit" class="btn btn-primary btn-lg">
                          Guardar cambios
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
    </section> 


{% endblock %}

proyecto_inmuebles/gestion_inmuebles/templates/arrendador.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Búsqueda de Ciudad</title>
    <script src="{% static 'js/buscadorciudad.js' %}"></script> <!-- Incluye tu archivo JS -->
</head>
<body>
    <div>
        <input type="text" id="buscar-ciudad" placeholder="Escribe una ciudad..." autocomplete="off">
        <div id="resultados"></div>
    </div>
</body>
</html>

proyecto_inmuebles/gestion_inmuebles/templates/contacto.html
{% extends "layout/base.html"%} {% block content %}{% load crispy_forms_tags %}

<div class="row">
  <div class="col-12 col-md-6 offset-md-3 mb-5">
    <div class="card mt-5">
      <div class="card-body">
        <h2 class="mb-3">Contácto</h2>

        <form action="" method="post">
          {% csrf_token %} {{ form | crispy }}

          <button type="submit" class="btn btn-success text_center">
            Enviar
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

proyecto_inmuebles/gestion_inmuebles/templates/contactoM.html
{% extends "layout/base.html"%} {% block content %}{% load crispy_forms_tags %}

<div class="row justify-content-center">
  <div class="col-12 col-md-8 col-lg-6 mb-5">
    <div class="card shadow-lg border-0 mt-5">
      <div class="card-body p-5">
        <h2 class="mb-4 text-center text-primary">Contáctanos</h2>
        <form action="" method="post">
          {% csrf_token %} {{ form | crispy }}

          <div class="d-grid gap-2 mt-4">
            <button type="submit" class="btn btn-primary btn-lg">
              Enviar Mensaje
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

proyecto_inmuebles/gestion_inmuebles/templates/exito.html
{% extends "layout/base.html"%} {% block content %} {% load static %}
<div class="text-center mt-5 mb-5">
  <h3>Gracias por contactarte con nosotros, te responderemos en breve</h3>
  <a href="{% url 'indice' %}" class="btn btn-primary">Volver al inicio</a>
</div>
{% endblock %}